// <auto-generated />
namespace MasterYodaAPI.DataAdapterLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addcarrera : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addcarrera));
        
        string IMigrationMetadata.Id
        {
            get { return "201602020244305_Addcarrera"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
